[project]
# The name of your game's executable. This should only contain a-z, A-Z, 0-9, _ or -.
name = "sokoban"
# The game's title. This will show up in the tile bar of your executable.
title = "Dragonruby Sokoban"
version = "0.1.0"
authors = ["Mathias Karstaedt <mathias.karstaedt@gmail.com>"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "2.26"
edition = "standard"

[dependencies]
draco = "https://github.com/guitsaru/draco.git"

[itch]
# The Project URL you set when you created the game on Itch.io. https://my-username.itch.io/my-game.
# This will also be the name of your build files, so fill it out even if you aren't uploading to Itch.io.
url = "dragonruby-sokoban"
# Your username on Itch.io.
username = "webmatze"
